/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionRouteImport } from './routes/terms-and-condition'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard/profile'
import { Route as AuthenticatedDashboardPricingRouteImport } from './routes/_authenticated/dashboard/pricing'
import { Route as AuthenticatedDashboardPrebuiltRouteImport } from './routes/_authenticated/dashboard/prebuilt'
import { Route as AuthenticatedDashboardMyProjectsRouteImport } from './routes/_authenticated/dashboard/my-projects'
import { Route as AuthenticatedDashboardPrebuiltIndexRouteImport } from './routes/_authenticated/dashboard/prebuilt/index'
import { Route as AuthenticatedDashboardProjectIdRouteImport } from './routes/_authenticated/dashboard/project.$id'
import { Route as AuthenticatedDashboardPrebuiltSlugRouteImport } from './routes/_authenticated/dashboard/prebuilt/$slug'

const TermsAndConditionRoute = TermsAndConditionRouteImport.update({
  id: '/terms-and-condition',
  path: '/terms-and-condition',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPricingRoute =
  AuthenticatedDashboardPricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPrebuiltRoute =
  AuthenticatedDashboardPrebuiltRouteImport.update({
    id: '/prebuilt',
    path: '/prebuilt',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMyProjectsRoute =
  AuthenticatedDashboardMyProjectsRouteImport.update({
    id: '/my-projects',
    path: '/my-projects',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPrebuiltIndexRoute =
  AuthenticatedDashboardPrebuiltIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardPrebuiltRoute,
  } as any)
const AuthenticatedDashboardProjectIdRoute =
  AuthenticatedDashboardProjectIdRouteImport.update({
    id: '/project/$id',
    path: '/project/$id',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPrebuiltSlugRoute =
  AuthenticatedDashboardPrebuiltSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedDashboardPrebuiltRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/refund': typeof RefundRoute
  '/terms-and-condition': typeof TermsAndConditionRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/my-projects': typeof AuthenticatedDashboardMyProjectsRoute
  '/dashboard/prebuilt': typeof AuthenticatedDashboardPrebuiltRouteWithChildren
  '/dashboard/pricing': typeof AuthenticatedDashboardPricingRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/prebuilt/$slug': typeof AuthenticatedDashboardPrebuiltSlugRoute
  '/dashboard/project/$id': typeof AuthenticatedDashboardProjectIdRoute
  '/dashboard/prebuilt/': typeof AuthenticatedDashboardPrebuiltIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/refund': typeof RefundRoute
  '/terms-and-condition': typeof TermsAndConditionRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard/my-projects': typeof AuthenticatedDashboardMyProjectsRoute
  '/dashboard/pricing': typeof AuthenticatedDashboardPricingRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/prebuilt/$slug': typeof AuthenticatedDashboardPrebuiltSlugRoute
  '/dashboard/project/$id': typeof AuthenticatedDashboardProjectIdRoute
  '/dashboard/prebuilt': typeof AuthenticatedDashboardPrebuiltIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/refund': typeof RefundRoute
  '/terms-and-condition': typeof TermsAndConditionRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/dashboard/my-projects': typeof AuthenticatedDashboardMyProjectsRoute
  '/_authenticated/dashboard/prebuilt': typeof AuthenticatedDashboardPrebuiltRouteWithChildren
  '/_authenticated/dashboard/pricing': typeof AuthenticatedDashboardPricingRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/prebuilt/$slug': typeof AuthenticatedDashboardPrebuiltSlugRoute
  '/_authenticated/dashboard/project/$id': typeof AuthenticatedDashboardProjectIdRoute
  '/_authenticated/dashboard/prebuilt/': typeof AuthenticatedDashboardPrebuiltIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/projects'
    | '/refund'
    | '/terms-and-condition'
    | '/dashboard'
    | '/api/chat'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/blog/'
    | '/dashboard/my-projects'
    | '/dashboard/prebuilt'
    | '/dashboard/pricing'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/dashboard/prebuilt/$slug'
    | '/dashboard/project/$id'
    | '/dashboard/prebuilt/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/projects'
    | '/refund'
    | '/terms-and-condition'
    | '/api/chat'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/blog'
    | '/dashboard/my-projects'
    | '/dashboard/pricing'
    | '/dashboard/profile'
    | '/dashboard'
    | '/dashboard/prebuilt/$slug'
    | '/dashboard/project/$id'
    | '/dashboard/prebuilt'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/projects'
    | '/refund'
    | '/terms-and-condition'
    | '/_authenticated/dashboard'
    | '/api/chat'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/blog/'
    | '/_authenticated/dashboard/my-projects'
    | '/_authenticated/dashboard/prebuilt'
    | '/_authenticated/dashboard/pricing'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/prebuilt/$slug'
    | '/_authenticated/dashboard/project/$id'
    | '/_authenticated/dashboard/prebuilt/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RefundRoute: typeof RefundRoute
  TermsAndConditionRoute: typeof TermsAndConditionRoute
  ApiChatRoute: typeof ApiChatRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-condition': {
      id: '/terms-and-condition'
      path: '/terms-and-condition'
      fullPath: '/terms-and-condition'
      preLoaderRoute: typeof TermsAndConditionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/pricing': {
      id: '/_authenticated/dashboard/pricing'
      path: '/pricing'
      fullPath: '/dashboard/pricing'
      preLoaderRoute: typeof AuthenticatedDashboardPricingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/prebuilt': {
      id: '/_authenticated/dashboard/prebuilt'
      path: '/prebuilt'
      fullPath: '/dashboard/prebuilt'
      preLoaderRoute: typeof AuthenticatedDashboardPrebuiltRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/my-projects': {
      id: '/_authenticated/dashboard/my-projects'
      path: '/my-projects'
      fullPath: '/dashboard/my-projects'
      preLoaderRoute: typeof AuthenticatedDashboardMyProjectsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/prebuilt/': {
      id: '/_authenticated/dashboard/prebuilt/'
      path: '/'
      fullPath: '/dashboard/prebuilt/'
      preLoaderRoute: typeof AuthenticatedDashboardPrebuiltIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardPrebuiltRoute
    }
    '/_authenticated/dashboard/project/$id': {
      id: '/_authenticated/dashboard/project/$id'
      path: '/project/$id'
      fullPath: '/dashboard/project/$id'
      preLoaderRoute: typeof AuthenticatedDashboardProjectIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/prebuilt/$slug': {
      id: '/_authenticated/dashboard/prebuilt/$slug'
      path: '/$slug'
      fullPath: '/dashboard/prebuilt/$slug'
      preLoaderRoute: typeof AuthenticatedDashboardPrebuiltSlugRouteImport
      parentRoute: typeof AuthenticatedDashboardPrebuiltRoute
    }
  }
}

interface AuthenticatedDashboardPrebuiltRouteChildren {
  AuthenticatedDashboardPrebuiltSlugRoute: typeof AuthenticatedDashboardPrebuiltSlugRoute
  AuthenticatedDashboardPrebuiltIndexRoute: typeof AuthenticatedDashboardPrebuiltIndexRoute
}

const AuthenticatedDashboardPrebuiltRouteChildren: AuthenticatedDashboardPrebuiltRouteChildren =
  {
    AuthenticatedDashboardPrebuiltSlugRoute:
      AuthenticatedDashboardPrebuiltSlugRoute,
    AuthenticatedDashboardPrebuiltIndexRoute:
      AuthenticatedDashboardPrebuiltIndexRoute,
  }

const AuthenticatedDashboardPrebuiltRouteWithChildren =
  AuthenticatedDashboardPrebuiltRoute._addFileChildren(
    AuthenticatedDashboardPrebuiltRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardMyProjectsRoute: typeof AuthenticatedDashboardMyProjectsRoute
  AuthenticatedDashboardPrebuiltRoute: typeof AuthenticatedDashboardPrebuiltRouteWithChildren
  AuthenticatedDashboardPricingRoute: typeof AuthenticatedDashboardPricingRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardProjectIdRoute: typeof AuthenticatedDashboardProjectIdRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardMyProjectsRoute:
      AuthenticatedDashboardMyProjectsRoute,
    AuthenticatedDashboardPrebuiltRoute:
      AuthenticatedDashboardPrebuiltRouteWithChildren,
    AuthenticatedDashboardPricingRoute: AuthenticatedDashboardPricingRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardProjectIdRoute: AuthenticatedDashboardProjectIdRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RefundRoute: RefundRoute,
  TermsAndConditionRoute: TermsAndConditionRoute,
  ApiChatRoute: ApiChatRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
